# Generated by Django 4.1.2 on 2023-06-12 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dep_image", models.ImageField(upload_to="departments")),
                ("dep_name", models.CharField(max_length=100)),
                ("dep_description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_name", models.CharField(max_length=255)),
                ("doc_spec", models.CharField(max_length=255)),
                ("doc_image", models.ImageField(upload_to="doctors")),
                (
                    "dep_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.departments",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pat_name", models.CharField(max_length=255)),
                ("pat_age", models.IntegerField()),
                ("pat_phone", models.CharField(max_length=255)),
                ("pat_email", models.EmailField(max_length=254)),
                ("book_date", models.DateField()),
                ("booked_on", models.DateField(auto_now=True)),
                (
                    "doc_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.doctors"
                    ),
                ),
            ],
        ),
    ]
