# Generated by Django 4.1.2 on 2023-06-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_booking_book_date_alter_booking_pat_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="doc_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.doctors",
            ),
        ),
    ]
